[config]
templates_dir = "~/.config/matugen/templates"

# --- GTK theming ---
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors/colors.css'

# --- Hyprland ---
[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

# --- Quickshell ---
[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell/Theme.qml"
output_path = "~/.config/quickshell/theme/Theme.qml"

# --- Kitty ---
[templates.kitty]
input_path = "~/.config/matugen/templates/kitty/theme.conf"
output_path = "~/.config/kitty/theme.conf"

# --- Starship ---
[templates.starship]
input_path = '~/.config/matugen/templates/starship/starship.toml'
output_path = '~/.config/starship/starship.toml'
