format = """
$directory\
$git_branch\
$git_status\
$jobs\
$fill\
$lua\
$nodejs\
$bun\
$golang\
$rust\
$docker_context\
$line_break\
$python\
$character\
"""

palette = 'colors'

[palettes.colors]
# Primary colors
accent = '#94cdf7'
accent-fixed = '#94cdf7'

# Secondary colors
secondary = '#b7c9d9'
secondary-fixed = '#b7c9d9'

# Tertiary colors
tertiary = '#cec0e8'
tertiary-fixed = '#cec0e8'

# Background colors
bg = '#101417'
bg-dim = '#101417'

# Foreground colors
fg = '#dfe3e8'
fg-strong = '#00344d'
fg-muted = '#c1c7ce'

[fill]
symbol = ' '

[git_branch]
style = 'fg:accent'
symbol = 'ï˜ '
format = '[on](fg:accent) [$symbol$branch ]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
staged = 'ó°•'
deleted = 'ï€'
untracked = 'ï„¨'
modified = 'ï„ª'
conflicted = 'î·¶'
ahead = 'ï…¶'
behind = 'ï…µ'
diverged = 'ï½'

[docker_context]
symbol = 'ğŸ‹'
style = 'fg:accent'
format = '[$symbol] ($style) $context'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[golang]
symbol = 'ğŸ¦«'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[lua]
symbol = 'ğŸŒ™'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[nodejs]
symbol = 'ğŸ¥¬'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[bun]
symbol = 'ğŸ¥'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[rust]
symbol = 'ğŸ¦€'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[python]
symbol = 'ğŸ'
style = 'bold fg:accent'
format = '[$symbol ($version) ($virtualenv)]($style)'
