format = """
$directory\
$git_branch\
$git_status\
$jobs\
$fill\
$lua\
$nodejs\
$bun\
$golang\
$rust\
$docker_context\
$line_break\
$python\
$character\
"""

palette = 'colors'

[palettes.colors]
# Primary colors
accent = '{{colors.primary.default.hex}}'
accent-fixed = '{{colors.primary_fixed_dim.default.hex}}'

# Secondary colors
secondary = '{{colors.secondary.default.hex}}'
secondary-fixed = '{{colors.secondary_fixed_dim.default.hex}}'

# Tertiary colors
tertiary = '{{colors.tertiary.default.hex}}'
tertiary-fixed = '{{colors.tertiary_fixed_dim.default.hex}}'

# Background colors
bg = '{{colors.surface.default.hex}}'
bg-dim = '{{colors.surface_dim.default.hex}}'

# Foreground colors
fg = '{{colors.on_surface.default.hex}}'
fg-strong = '{{colors.on_primary.default.hex}}'
fg-muted = '{{colors.on_surface_variant.default.hex}}'

[fill]
symbol = ' '

[git_branch]
style = 'fg:accent'
symbol = 'ï˜ '
format = '[on](fg:accent) [$symbol$branch ]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
staged = 'ó°•'
deleted = 'ï€'
untracked = 'ï„¨'
modified = 'ï„ª'
conflicted = 'î·¶'
ahead = 'ï…¶'
behind = 'ï…µ'
diverged = 'ï½'

[docker_context]
symbol = 'ğŸ‹'
style = 'fg:accent'
format = '[$symbol] ($style) $context'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[golang]
symbol = 'ğŸ¦«'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[lua]
symbol = 'ğŸŒ™'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[nodejs]
symbol = 'ğŸ¥¬'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[bun]
symbol = 'ğŸ¥'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[rust]
symbol = 'ğŸ¦€'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[python]
symbol = 'ğŸ'
style = 'bold fg:accent'
format = '[$symbol ($version) ($virtualenv)]($style)'
