format = """
$directory\
$git_branch\
$git_status\
$jobs\
$fill\
$lua\
$nodejs\
$bun\
$golang\
$rust\
$docker_context\
$line_break\
$python\
$character\
"""

palette = 'colors'

[palettes.colors]
accent = '#8fbcbb'
accent-fixed = '#88c0d0'
secondary = '#81a1c1'
secondary-fixed = '#5e81ac'
tertiary = '#a3be8c'
tertiary-fixed = '#b48ead'
bg = '#2e3440'
bg-dim = '0e1115'
fg = '#d8dee9'
fg-strong = '#eceff4' 
fg-muted = '#e5e9f0'

[fill]
symbol = ' '

[git_branch]
style = 'fg:accent'
symbol = 'ï˜ '
format = '[on](color8) [$symbol$branch ]($style)'

style = 'fg:fg'
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
staged = 'ó°•'
deleted = 'ï€'
untracked = 'ï„¨'
modified = 'ï„ª'
conflicted = 'î·¶'
ahead = 'ï…¶'
behind = 'ï…µ'
diverged = 'ï½'

[docker_context]
symbol = 'ğŸ‹'
style = 'fg:accent'
format = '[$symbol] ($style) $context'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[golang]
symbol = 'ğŸ¦«'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[lua]
symbol = 'ğŸŒ™'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[nodejs]
symbol = 'ğŸ¥¬'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[bun]
symbol = 'ğŸ¥'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[rust]
symbol = 'ğŸ¦€'
style = 'bold fg:accent'
format = '[$symbol ($version)]($style)'

[python]
symbol = 'ğŸ'
style = 'bold fg:accent'
format = '[$symbol ($version) ($virtualenv)]($style)'
